import { ERROR_CODES } from '../protocol/errors.js';

// Public contract: documented in docs/USAGE.md ("Exit Codes"). Keep in sync.
const EXIT_CODE_BY_ERROR_CODE: Readonly<Record<string, number>> = Object.freeze(
  {
    [ERROR_CODES.INVALID_SESSION_ID]: 2,
    [ERROR_CODES.INVALID_DIMENSIONS]: 2,
    [ERROR_CODES.INVALID_SIGNAL]: 2,
    [ERROR_CODES.INVALID_KEYS]: 2,
    [ERROR_CODES.INVALID_DURATION]: 2,
    [ERROR_CODES.INVALID_INPUT]: 2,
    [ERROR_CODES.SESSION_NOT_FOUND]: 3,
    [ERROR_CODES.SESSION_NOT_RUNNING]: 4,
    [ERROR_CODES.SESSION_ALREADY_DESTROYED]: 4,
    [ERROR_CODES.HOST_TIMEOUT]: 5,
    [ERROR_CODES.HOST_UNREACHABLE]: 6,
    [ERROR_CODES.EXPORT_ERROR]: 7,
    [ERROR_CODES.STORAGE_READ_ERROR]: 8,
    [ERROR_CODES.STORAGE_WRITE_ERROR]: 8,
    [ERROR_CODES.MANIFEST_VALIDATION_ERROR]: 8,
    [ERROR_CODES.PROTOCOL_ERROR]: 9,
    [ERROR_CODES.RPC_ERROR]: 9,
    [ERROR_CODES.REPLAY_ERROR]: 10,
    [ERROR_CODES.WAIT_TIMEOUT]: 11,
    [ERROR_CODES.CAPABILITY_UNAVAILABLE]: 12,
    [ERROR_CODES.INTERNAL_ERROR]: 1,
  },
);

export function exitCodeForError(code: string): number {
  return EXIT_CODE_BY_ERROR_CODE[code] ?? 1;
}
